macro_rules! command_ids {
    ($(($variant:ident, $name:literal)),+ $(,)?) => {
        #[derive(Clone, Copy, Debug, PartialEq, Eq)]
        pub enum CommandId {
            Unknown,
            $( $variant, )+
        }

        impl CommandId {
            pub const ALL: &'static [Self] = &[
                $( Self::$variant, )+
            ];

            #[inline(always)]
            pub fn name(self) -> Option<&'static str> {
                Some(match self {
                    Self::Unknown => return None,
                    $( Self::$variant => $name, )+
                })
            }
        }
    };
}

command_ids!(
    (Auth, "AUTH"),
    (Hello, "HELLO"),
    (Client, "CLIENT"),
    (Command, "COMMAND"),
    (Select, "SELECT"),
    (Quit, "QUIT"),
    (Ping, "PING"),
    (Echo, "ECHO"),
    (Eval, "EVAL"),
    (EvalRo, "EVAL_RO"),
    (EvalSha, "EVALSHA"),
    (EvalShaRo, "EVALSHA_RO"),
    (Script, "SCRIPT"),
    (Del, "DEL"),
    (Exists, "EXISTS"),
    (Touch, "TOUCH"),
    (Unlink, "UNLINK"),
    (Type, "TYPE"),
    (Rename, "RENAME"),
    (RenameNx, "RENAMENX"),
    (DbSize, "DBSIZE"),
    (Keys, "KEYS"),
    (Scan, "SCAN"),
    (Move, "MOVE"),
    (Dump, "DUMP"),
    (Restore, "RESTORE"),
    (Sort, "SORT"),
    (Copy, "COPY"),
    (FlushDb, "FLUSHDB"),
    (FlushAll, "FLUSHALL"),
    (Expire, "EXPIRE"),
    (PExpire, "PEXPIRE"),
    (ExpireAt, "EXPIREAT"),
    (PExpireAt, "PEXPIREAT"),
    (Persist, "PERSIST"),
    (Ttl, "TTL"),
    (PTtl, "PTTL"),
    (Get, "GET"),
    (Set, "SET"),
    (SetNx, "SETNX"),
    (GetSet, "GETSET"),
    (GetDel, "GETDEL"),
    (SetEx, "SETEX"),
    (PSetEx, "PSETEX"),
    (GetEx, "GETEX"),
    (Delex, "DELEX"),
    (Digest, "DIGEST"),
    (Append, "APPEND"),
    (SubStr, "SUBSTR"),
    (StrLen, "STRLEN"),
    (SetRange, "SETRANGE"),
    (GetRange, "GETRANGE"),
    (Lcs, "LCS"),
    (MGet, "MGET"),
    (MSet, "MSET"),
    (MSetEx, "MSETEX"),
    (MSetNx, "MSETNX"),
    (Incr, "INCR"),
    (IncrBy, "INCRBY"),
    (IncrByFloat, "INCRBYFLOAT"),
    (Decr, "DECR"),
    (DecrBy, "DECRBY"),
    (SetBit, "SETBIT"),
    (GetBit, "GETBIT"),
    (BitCount, "BITCOUNT"),
    (BitPos, "BITPOS"),
    (BitOp, "BITOP"),
    (BitField, "BITFIELD"),
    (BitFieldRo, "BITFIELD_RO"),
    (PfAdd, "PFADD"),
    (PfCount, "PFCOUNT"),
    (PfMerge, "PFMERGE"),
    (HSet, "HSET"),
    (HMSet, "HMSET"),
    (HSetNx, "HSETNX"),
    (HGet, "HGET"),
    (HMGet, "HMGET"),
    (HGetAll, "HGETALL"),
    (HDel, "HDEL"),
    (HExists, "HEXISTS"),
    (HKeys, "HKEYS"),
    (HVals, "HVALS"),
    (HLen, "HLEN"),
    (HStrLen, "HSTRLEN"),
    (HIncrBy, "HINCRBY"),
    (HIncrByFloat, "HINCRBYFLOAT"),
    (HScan, "HSCAN"),
    (HRandField, "HRANDFIELD"),
    (LPush, "LPUSH"),
    (LPushX, "LPUSHX"),
    (RPush, "RPUSH"),
    (RPushX, "RPUSHX"),
    (LPop, "LPOP"),
    (RPop, "RPOP"),
    (LRem, "LREM"),
    (LLen, "LLEN"),
    (LIndex, "LINDEX"),
    (LRange, "LRANGE"),
    (LSet, "LSET"),
    (LTrim, "LTRIM"),
    (LInsert, "LINSERT"),
    (LPos, "LPOS"),
    (LMove, "LMOVE"),
    (LMPop, "LMPOP"),
    (BLPop, "BLPOP"),
    (BRPop, "BRPOP"),
    (BLMPop, "BLMPOP"),
    (BRPopLPush, "BRPOPLPUSH"),
    (RPopLPush, "RPOPLPUSH"),
    (SAdd, "SADD"),
    (SRem, "SREM"),
    (SMembers, "SMEMBERS"),
    (SCard, "SCARD"),
    (SMove, "SMOVE"),
    (SPop, "SPOP"),
    (SInter, "SINTER"),
    (SUnion, "SUNION"),
    (SDiff, "SDIFF"),
    (SScan, "SSCAN"),
    (SIsMember, "SISMEMBER"),
    (SMIsMember, "SMISMEMBER"),
    (SDiffStore, "SDIFFSTORE"),
    (SInterCard, "SINTERCARD"),
    (SInterStore, "SINTERSTORE"),
    (SUnionStore, "SUNIONSTORE"),
    (SRandMember, "SRANDMEMBER"),
    (ZAdd, "ZADD"),
    (ZRem, "ZREM"),
    (ZCard, "ZCARD"),
    (ZCount, "ZCOUNT"),
    (ZScore, "ZSCORE"),
    (ZRank, "ZRANK"),
    (ZRevRank, "ZREVRANK"),
    (ZIncrBy, "ZINCRBY"),
    (ZMScore, "ZMSCORE"),
    (ZRange, "ZRANGE"),
    (ZRevRange, "ZREVRANGE"),
    (ZPopMin, "ZPOPMIN"),
    (ZPopMax, "ZPOPMAX"),
    (BZPopMin, "BZPOPMIN"),
    (BZPopMax, "BZPOPMAX"),
    (ZMPop, "ZMPOP"),
    (BZMPop, "BZMPOP"),
    (ZInter, "ZINTER"),
    (ZInterStore, "ZINTERSTORE"),
    (ZUnion, "ZUNION"),
    (ZUnionStore, "ZUNIONSTORE"),
    (ZDiff, "ZDIFF"),
    (ZDiffStore, "ZDIFFSTORE"),
    (ZScan, "ZSCAN"),
    (ZRandMember, "ZRANDMEMBER"),
    (ZRangeStore, "ZRANGESTORE"),
    (ZRangeByScore, "ZRANGEBYSCORE"),
    (ZRangeByLex, "ZRANGEBYLEX"),
    (ZRevRangeByScore, "ZREVRANGEBYSCORE"),
    (ZRevRangeByLex, "ZREVRANGEBYLEX"),
    (ZLexCount, "ZLEXCOUNT"),
    (ZRemRangeByLex, "ZREMRANGEBYLEX"),
    (ZRemRangeByRank, "ZREMRANGEBYRANK"),
    (ZRemRangeByScore, "ZREMRANGEBYSCORE"),
    (GeoAdd, "GEOADD"),
    (GeoPos, "GEOPOS"),
    (GeoDist, "GEODIST"),
    (GeoHash, "GEOHASH"),
    (GeoRadius, "GEORADIUS"),
    (GeoRadiusRo, "GEORADIUS_RO"),
    (GeoSearch, "GEOSEARCH"),
    (GeoSearchStore, "GEOSEARCHSTORE"),
    (GeoRadiusByMember, "GEORADIUSBYMEMBER"),
    (GeoRadiusByMemberRo, "GEORADIUSBYMEMBER_RO"),
    (XAdd, "XADD"),
    (XLen, "XLEN"),
    (XDel, "XDEL"),
    (XRange, "XRANGE"),
    (XRevRange, "XREVRANGE"),
    (XTrim, "XTRIM"),
    (XRead, "XREAD"),
    (XGroup, "XGROUP"),
    (XAck, "XACK"),
    (XClaim, "XCLAIM"),
    (XPending, "XPENDING"),
    (XReadGroup, "XREADGROUP"),
    (XAutoClaim, "XAUTOCLAIM"),
    (JsonArrAppend, "JSON.ARRAPPEND"),
    (JsonArrIndex, "JSON.ARRINDEX"),
    (JsonArrInsert, "JSON.ARRINSERT"),
    (JsonArrLen, "JSON.ARRLEN"),
    (JsonArrPop, "JSON.ARRPOP"),
    (JsonArrTrim, "JSON.ARRTRIM"),
    (JsonClear, "JSON.CLEAR"),
    (JsonDebug, "JSON.DEBUG"),
    (JsonDel, "JSON.DEL"),
    (JsonForget, "JSON.FORGET"),
    (JsonGet, "JSON.GET"),
    (JsonMerge, "JSON.MERGE"),
    (JsonMGet, "JSON.MGET"),
    (JsonMSet, "JSON.MSET"),
    (JsonNumIncrBy, "JSON.NUMINCRBY"),
    (JsonNumMultBy, "JSON.NUMMULTBY"),
    (JsonObjKeys, "JSON.OBJKEYS"),
    (JsonObjLen, "JSON.OBJLEN"),
    (JsonResp, "JSON.RESP"),
    (JsonSet, "JSON.SET"),
    (JsonStrAppend, "JSON.STRAPPEND"),
    (JsonStrLen, "JSON.STRLEN"),
    (JsonToggle, "JSON.TOGGLE"),
    (JsonType, "JSON.TYPE"),
    (Acl, "ACL"),
    (Config, "CONFIG"),
    (Publish, "PUBLISH"),
    (Subscribe, "SUBSCRIBE"),
    (Unsubscribe, "UNSUBSCRIBE"),
    (PSubscribe, "PSUBSCRIBE"),
    (PUnsubscribe, "PUNSUBSCRIBE"),
    (PubSub, "PUBSUB"),
    (Multi, "MULTI"),
    (Exec, "EXEC"),
    (Discard, "DISCARD"),
    (Watch, "WATCH"),
    (Unwatch, "UNWATCH"),
);
